### ISSUE TITLE
Definitions not always pulling in other definitions

### ISSUE THREAD

**Issue by EmmaJP** [act-rules/act-rules-web#120]
It is a little confusing when editing definitions for act-rules that links within those definitions are relative, linking to other definitions that are not within that file. With some realisation that these code snippets are being pulled into rules, it makes a little more sense.

However, it does not always work as expected. Possibly when the referenced definitions are not included in a rule because the rule itself does not mention them. This is particularly noticeable with rules that reference semantic role, which in turn references explicit semantic role and implicit semantic role (mentioned in https://github.com/act-rules/act-rules.github.io/issues/1129).

**Comment by Jym77** [comment]
See also #23

**Comment by jkodu** [comment]
Duplicate issue - https://github.com/act-rules/act-rules-web/issues/23, closing
