### ISSUE TITLE
Change implementations table for rules

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules-web#126]
Each rules page has an "implementations" heading, the table shown on that page should be updated to look like the following:

| Implementor | Consistency          | Complete | report      |
|-------------|----------------------|----------|-------------|
| My Tool     | Consistent           | yes      | View report |
| Third tool  | Consistent           | no       | View report |
| Other toool | Partially consistent | yes      | View report |

The "complete" shows total number of test cases compare to the number of cases that do **not** have "untested".

The table must be sorted:
1. consistent before partially consistent
2. Complete before incomplete

The table includes all implementors that did not get "inconsitent" as its result

**Comment by jkodu** [comment]
PR in place. Closing issue.

**Comment by jkodu** [comment]
PR in place. Closing issue.
