### ISSUE TITLE
"last modified" date is incorrect

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules-web#128]
This rule has a "last modified" data of Sep 25, 2019, whereas the actual last change was on January 21st 2020:

- https://act-rules.github.io/rules/b33eff
- https://github.com/act-rules/act-rules.github.io/commits/develop/_rules/css-restrict-orientation-b33eff.md

**Comment by WilcoFiers** [comment]
It looks like this problem is related to the changelog, which does not seem to get updated.

**Comment by jkodu** [comment]
My suspicion is `git log` even with a `--follow` command does not actually get all the logs since the filenames changed.

Further investigation is necessary.

**Comment by jkodu** [comment]
Related issue - https://github.com/act-rules/act-rules-web/issues/114
