### ISSUE TITLE
Sort rules alphabetically, not asciibetically

### ISSUE THREAD

**Issue by Jym77** [act-rules/act-rules-web#138]
Rules in the rule page (https://act-rules.github.io/rules/) are sorted ASCIIbetically (uppercase, then backtick, then lowercase) which is somewhat confusing as a rule such as "audio or video …" is all the way down, and "`aria-*` …" in the middle due to the leading backtick.

I suggest we ignore the leading backtick when sorting rules and sort alphabetically (so that "`aria-*` …" is together with the other "ARIA …" rules).

**Comment by jkodu** [comment]
PR in place. Closing issue.
