### ISSUE TITLE
Support "acknowledgments" key in rules

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules-web#142]
The current expected key is "acknowledgements", this should be "acknowledgments" (without the second E). We should update the site so that either one can be used. We can then transition away from "acknowledgements" in the rules.

**Comment by EmmaJP** [comment]
Refer https://www.w3.org/TR/act-rules-format/#acknowledgements

And https://en.wikipedia.org/wiki/Wikipedia:Manual_of_Style/Spelling#Preferred_variants

**Comment by Jym77** [comment]
W3C publications are normally written in colonial English (and we do try and follow that rule)…
I guess the ACT rules format will also have to change…

**Comment by jkodu** [comment]
Related PR - https://github.com/act-rules/act-rules-web/pull/143

**Comment by jkodu** [comment]
I will keep this issue open to discuss this comment - https://github.com/act-rules/act-rules-web/issues/142#issuecomment-593456663

**Comment by WilcoFiers** [comment]
yeah, this is incorrect in the rules format too then. Hadn't realised it... Until that spellchecker reported it, I had no idea you could even spell acknowledgment with only two E's.
