### ISSUE TITLE
Improve the accessibility requirements mapping

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules-web#149]
Instead of saying "not satisfied" or "further testing is needed" AG suggested specifying what is not satisfied / needs further testing. This would become:

- [success criterion / technique / requirement] is not satisfied
- [success criterion / technique / requirement] is satisfied
- [success criterion / technique / requirement] needs further testing

Ideally we'd do this without a change to the template.

**Comment by jkodu** [comment]
PR in place. Closing issue.
