### ISSUE TITLE
Check if a doctype exists before adding it to an example

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules-web#183]
It looks like in this code, DOCTYPE is added regardless of if the code snippet already has one. That's fairly error prone. We should first check for a doctype, and only if there isn't one add it in:

https://github.com/act-rules/act-rules-web/blob/3cb73b7cb5e3a39b6c342fcb7a89ab6551dcbc32/build/create-testcases.js

**Comment by jkodu** [comment]
Fixed in https://github.com/act-rules/act-rules-web/pull/188

**Comment by carlosapaduarte** [comment]
It looks this hasn't been completely solved. In this test case there are still two DOCTYPE in the response payload: https://act-rules.github.io/testcases/5b7ae0/24fd835bb3314fafe0c822f640869bb93dae23d3.xhtml

**Comment by jeeyyy** [comment]
@carlosapaduarte I am seeing the [source](view-source:https://act-rules.github.io/testcases/5b7ae0/24fd835bb3314fafe0c822f640869bb93dae23d3.xhtml) of the above example. I see only one DOCTYPE. What am I missing?

**Comment by carlosapaduarte** [comment]
@jeeyyy can't replicate it anymore. I'm closing the issue.
