### ISSUE TITLE
Layout of 404 page is broken

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules-web#185]
The `main > section` element has flex-direction row, I'm guessing because of the ToC. On a 404 page the content inside the section should be wrapped so the `h1` and the `p` don't end up on the same line:

See https://act-rules.github.io/rules/4c31df/rules/80f0bf for example.

**Comment by jkodu** [comment]
Fixed in https://github.com/act-rules/act-rules-web/pull/186, closing issue.
