### ISSUE TITLE
testcases.json and website out of date

### ISSUE THREAD

**Issue by dd8** [act-rules/act-rules-web#189]
Automatic rebuild seems broken - `testcases.json` is about a week out of date

HTTP headers in devtools shows
`last-modified: Mon, 08 Jun 2020 12:58:18 GMT`

Changes from PR https://github.com/act-rules/act-rules.github.io/pull/1309 and https://github.com/act-rules/act-rules.github.io/pull/1333 merges yesterday aren't showing up

https://act-rules.github.io/rules/e086e5 still shows the Inapplicable Example 3 and 4 from before the merge

Same problem with the examples 1333 fixes (old test cases still showing on website)

**Comment by jkodu** [comment]
Thanks @dd8 

This is a valid issue. I am looking into it. Thanks for reporting.

**Comment by jkodu** [comment]
I have got this fixed now. Thanks for notifying. Closing the issue now.
