### ISSUE TITLE
Lots of tests in rendered implementation report show as 'untested'

### ISSUE THREAD

**Issue by dd8** [act-rules/act-rules-web#190]
We currently have 6 test cases in report.json marked as "outcome": "earl:untested" but https://act-rules.github.io/implementation/sortsite shows 39 as untested  (these 6 correspond to testcases with github issues filed against them)

For example most of the tests for 'Link has non-empty accessible name' show as untested on the report page:
https://act-rules.github.io/implementation/sortsite#id-c487ae
but these these tests all have pass/fail results in our report.json

Passed Example 2 shows untested on the report page, but report.json shows "outcome": "earl:passed",
https://github.com/act-rules/act-rules-implementation-sortsite/blob/master/report.json#L10301
Failed Example 2 shows untested on the report page, but report.json shows "outcome": "earl:failed"
https://github.com/act-rules/act-rules-implementation-sortsite/blob/master/report.json#L9808

Doesn't seem to be a testcase hash mismatch, since the URLs in the report.json matches the URL displayed by 'Open in new tab' for the testcase 
https://act-rules.github.io/rules/c487ae#failed-example-2

report.json was last updated a week ago - is it a rebuild issue?

BTW might be worth including a visible update date and commit hash (either visible or hidden in HTML comment) on the rendered implementation reports to help debug stuff like this.

**Comment by jkodu** [comment]
@dd8 I think this has been a re-build issue.
I have now wired up the build process again. 

GitHub actions, seems to have a limitation to push cross repositories. I have worked around it now. Can you re-verify the test cases & let me know if there is still an issue?

**Comment by dd8** [comment]
@jkodu Thanks - the results are now what I expect. 

There are 8 showing as 'untested' instead of 6 but looks like this is due to new test cases published after our test report like:
https://act-rules.github.io/rules/b33eff/#failed-example-3
