### ISSUE TITLE
Glossary recursion

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules-web#23]
Definitions often include other definitions. Those recursively linked definitions need to be added to the rule. For example here:
https://auto-wcag.github.io/auto-wcag/rules/SC2-5-3-label-content-name-mismatch.html#visible-on-the-page

**Comment by Jym77** [comment]
This is still not working and currently (rightfully) blocking TF adoption of rules. See Kathy's last comment in https://github.com/w3c/wcag-act/issues/467

**Comment by jeeyyy** [comment]
PR in place - https://github.com/act-rules/act-rules-web/pull/209. Please re-open issue if need be.
