### ISSUE TITLE
WCAG non interference is not shown as a requirement

### ISSUE THREAD

**Issue by Jym77** [act-rules/act-rules-web#235]
[`audio` or `video` avoids automatically playing audio](https://act-rules.github.io/rules/80f0bf) has a mapping to WCAG non-interference. However, it is incorrectly shown as "Not required to conformance to any W3C accessibility recommendation."

In the [rule file](https://github.com/act-rules/act-rules.github.io/blob/develop/_rules/audio-or-video-avoids-automatically-playing-audio-80f0bf.md) this is correctly marked as `forConformance: true`, and as far as I understand [the code handling it](https://github.com/act-rules/act-rules-web/blob/develop/src/rule/get-accessibility-requirement.js) this should actually be enough to show it as required 🤔 

But it's apparently not working.

**Comment by carlosapaduarte** [comment]
Apparently it has been fixed. Closing
