### ISSUE TITLE
Acknowledgement for enabling funding

### ISSUE THREAD

**Issue by annethyme** [act-rules/act-rules-web#26]
I suggest that we add this to the Acknowledgements section for all rules that have been funded through the WAI-Tools project: 

## Authors

- ...

## Enabling funders

This rule has been developed with support from the [WAI-Tools Project](https://www.w3.org/WAI/about/projects/wai-tools/), co-funded by the European Commission (EC) under the Horizon 2020 Program (Grant Agreement 780057). The content of this rule does not necessarily reflect the views or policies of the European Commission (EC) or any of the European Union (EU) Member States

**Comment by jkodu** [comment]
@nitedog - `acknowledgement` section has been added to all rules, in the frontmatter.

This is also rendered on the site now. Now it is just a matter of adding sections like `funding`, `reviewers` and anything else we need in the rule frontmatter and it should show in the website.
