### ISSUE TITLE
Keyboard trap when accessing rule on github.io

### ISSUE THREAD

**Issue by moekraft** [act-rules/act-rules-web#31]
Open rule https://act-rules.github.io/rules/2779a5

On Safari, cannot scroll page unless focus is put on collapsible <summary> 2.4.2. Page Titled. Once focus is put on this element, next tab goes to browser url field. 

On Firefox, it's a little better but trap still exists:
- Can tab to page and scroll, however, tabbing focus around page does not advance to elements on page. It's a tight loop from page url, to menu, to page, to 2.4.2 Page Titled and then back to url. Cannot access other elements on page.

Note: In both browsers, cannot scroll page via the scroll bar.

**Comment by offsetChris** [comment]
Moved the work from the original repo here in pull request #34 . Please reopen if there are issues.
