### ISSUE TITLE
Enable gatsby previous/ next navigation buttons in rule page

### ISSUE THREAD

**Issue by jkodu** [act-rules/act-rules-web#37]
It would be nice to be able to navigation from one rule to next rule by having `previous`/ `next` rule buttons at the bottom of each rule page.

**Comment by jkodu** [comment]
I think Gatsby has some tricks up its sleeve to achieve this.

**Comment by WilcoFiers** [comment]
I don't think this makes sense. Rules aren't in any particular order, so there's no obvious previous or next rule.

**Comment by jkodu** [comment]
Ok. Navigation wise, it does makes it a bit hard to go back to rules page and come back to a rule. But yes, agreed rules are not in the right order to have this functionality.
