### ISSUE TITLE
Broken fields in testcases.json

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules-web#40]
https://act-rules.github.io/testcases.json

This:
>   "name": "[object Object] test cases",

And this:
>       "ruleAccessibilityRequirements": null

**Comment by jkodu** [comment]
@WilcoFiers 

This PR - https://github.com/act-rules/act-rules-web/pull/41, fixes the `name` attribute.

As for `ruleAccessibilityRequirements`, this is `null` for rule's that have an empty `accessibility_requirements:` in the frontmatter. This is true for some `ARIA` rules and some `media` rules.
