### ISSUE TITLE
Links from SC should resolve to WCAG21 (latest)

### ISSUE THREAD

**Issue by jkodu** [act-rules/act-rules-web#42]
Also see - https://github.com/act-rules/act-rules.github.io/issues/974

**Comment by offsetChris** [comment]
Emailed about this question as well. Do we want all SC links to point to WCAG21? Seems from the other repo conversations we want to maintain WCAG20 where applicable. Do you have any additional requirements for this issue you could post here?

**Comment by jkodu** [comment]
We basically do not want WCAG20 urls to be resolved from this screen. It is possible to resolve these are WCAG21 urls instead.

![image](https://user-images.githubusercontent.com/20978252/67562332-6a85b700-f716-11e9-8496-3f3c91ca31cc.png)

The magic for generating these URL's happens in `get-wcag-meta-data.js`

Changing the logic to use `id` where possible instead of `alt_id` will solve for this
![image](https://user-images.githubusercontent.com/20978252/67562424-91dc8400-f716-11e9-806c-d6e59213f8a6.png)

JSON in question we use is - https://raw.githubusercontent.com/w3c/wai-wcag-quickref/gh-pages/_data/wcag21.json

**Comment by jkodu** [comment]
PR in place, closing issue.
