### ISSUE TITLE
"Propose a change to the rule" links are broken

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules-web#44]
Here's what the links look like right now:

git+https://github.com/act-rules/act-rules.github.io.git/edit/develop/_rules/form-control-label-descriptive-cc0f0a.md

1. That `git+` bit doesn't belong there
2. That URL doesn't seem to work even without the `git+` bit

**Comment by jkodu** [comment]
PR in place. Closing issue.
