### ISSUE TITLE
Website has horizontal scrolling disabled

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules-web#50]
If you zoom in on the website beyond the point where the left navigation and the main content no longer fit in the width of the screen, content is clipped off the right edge of the screen. It is not possible to scroll content horizontally. **This is a failure of WCAG. Adding horizontal scrolling fixes the clipping issue, but will create two-dimentional scrolling which also is a failure of WCAG**.

**Comment by jkodu** [comment]
@offsetChris - FYI, seems like there is a problem with the scroll bug put in place.

**Comment by jkodu** [comment]
PR in place, closing issue.
