### ISSUE TITLE
Move Cotribute An Implementation

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules-web#72]
https://act-rules.github.io/pages/implementations/earl-reports/

Move the bottom part of the page to the top:

On Reporting Format, move this information from bottom to top so manual testers don't need to read all of it:If you have a tool that can return a data format, you will need to run your tests against the ACT-R test cases and submit a report.If you use manual test methodology, where you fill results into some report template or tool, you can Use the WCAG-EM Report Tool instead to produce implementation reports.
--

**Comment by jkodu** [comment]
PR in place - https://github.com/act-rules/act-rules.github.io/pull/1070

**Comment by jkodu** [comment]
@WilcoFiers 

The pages along with the rules and definitions exist within the other repo, so this issue should have been in the other repo.
