### ISSUE TITLE
Text at top of window overwrites rule text

### ISSUE THREAD

**Issue by moekraft** [act-rules/act-rules-web#87]
Text at top of window overwrites rule text making it difficult to read, "A Community Group of theWorld Wide Web Consortium.

Developed with the support of the EU-funded WAI-Tools Project."
<img width="619" alt="image" src="https://user-images.githubusercontent.com/12103268/70241008-461cf180-173c-11ea-992b-4b94173c404d.png">

**Comment by jkodu** [comment]
This issue has been solved, as we moved the text content back to the footer.
See - https://act-rules.github.io/

Please reopen if the issue can be recreated.
