### ISSUE TITLE
Incorrect test asset not caught by tests.

### ISSUE THREAD

**Issue by Jym77** [act-rules/act-rules-web#9]
In the current ACT-R repo, we have (at least) [one example (Inapplicable Example 3)](https://github.com/act-rules/act-rules.github.io/blob/develop/_rules/links-identical-name-equivalent-purpose-b20e66.md#inapplicable-example-3) with a wrong URL for a test asset ("pabe2" instead of "page2" for the second link in the example).

But the tests are not failing…

**Comment by jkodu** [comment]
PR in place https://github.com/act-rules/act-rules.github.io/pull/1040
Closing issue.
